server:
  port: 8000

spring:
  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/cities?useSSL=false&allowPublicKeyRetrieval=true
    initialization-mode: always